name: 'medicare_saf_connector'
version: '1.0.0'
config-version: 2


profile: 'default'                      

## Variables affecting the configuration of this project and the Tuva Project
## packages are below.
vars:

#########################################
#### Medicare SAF Project Variables ####
#########################################

  input_database: medicare_saf      
  input_schema:  raw_data

  output_database: medicare_saf
  output_schema: claims_data_model

  ## Source Table Names
  carrier_base_claim: "{{ source('saf','carrier_base_claim') }}"
  carrier_claim_line: "{{ source('saf','carrier_claim_line') }}"
  dme_base_claim: "{{ source('saf','dme_base_claim') }}"
  dme_claim_line: "{{ source('saf','dme_claim_line') }}"
  hha_base_claim: "{{ source('saf','hha_base_claim') }}"
  hha_revenue_center: "{{ source('saf','hha_revenue_center') }}"
  hospice_base_claim: "{{ source('saf','hospice_base_claim') }}"
  hospice_revenue_center: "{{ source('saf','hospice_revenue_center') }}"
  inpatient_base_claim: "{{ source('saf','inpatient_base_claim') }}"
  inpatient_revenue_center: "{{ source('saf','inpatient_revenue_center') }}"
  master_beneficiary_summary: "{{ source('saf','master_beneficiary_summary') }}"
  outpatient_base_claim: "{{ source('saf','outpatient_base_claim') }}"
  outpatient_revenue_center: "{{ source('saf','outpatient_revenue_center') }}"
  snf_base_claim: "{{ source('saf','snf_base_claim') }}"
  snf_revenue_center: "{{ source('saf','snf_revenue_center') }}"

########################################
#### Tuva Project Package Variables ####
########################################

## Package Enabled Variables:
## These variables tell the Tuva Project which packages you want
## to enable.  To enable a package set it to true, to disable a 
## package set it to false.
  claims_preprocessing_enabled: true
  cms_chronic_conditions_enabled: true
  data_profiling_enabled: true 
  pmpm_enabled: true
  readmissions_enabled: true
  terminology_enabled: true
  tuva_chronic_conditions_enabled: true


## Target Database Variable:
## This variable tells the Tuva Project where to write the 
## output data to.  You must create this database in your
## data warehouse before running the Tuva Project.
  tuva_database: medicare_saf  

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  medicare_saf_connector:
    +materialized: view
    core:
      +materialized: table